### ISSUE TITLE
Configuration for plain response object

### ISSUE THREAD

**Issue by crstnio** [thinhle-agilityio/gatsby-source-apiserver#16]
Hey,

first thank you for that source plugin!

Having some trouble setting up the configuration for my use case. I use [npms.io](https://npms.io/) to fetch multiple packages at once. The API responds with following structure in Postman when trying to get `react` and `lodash` packages:

```js
{
  "react": Object,
  "lodash": Object,
}
```

But in GraphQL, the nodes are as follows:

```graphql
{
  "data": {
    "allNpmsPackages": {
      "edges": [
        {
          "node": {
            "react": {
              ...
            },
            "lodash": {
              ...
            }
          }
        },
        {
          "node": {
            "react": null,
            "lodash": null
          }
        }
      ]
    }
  }
}
```

Each package should have its own node. I tried using an empty `entityLevel` and setting it to `data` only, but the latter returns an error.

**gatsby-config.js**

```js
    {
      resolve: `gatsby-source-apiserver`,
      options: {
        typePrefix: `npms__`,
        url: `https://api.npms.io/v2/package/mget`,
        method: `post`,
        headers: {
          Accept: `application/json`,
          'Content-Type': `application/json`,
        },
        data: [`react`, `lodash`],
        name: `Packages`,
        entityLevel: ``,
        verboseOutput: true,
      },
    },
```

Could you tell me what to configure in this scenario?

**Comment by cardiv** [comment]
I narrowed it down to the result being a single object. That is [packed into an array](https://github.com/thinhle-agilityio/gatsby-source-apiserver/blob/master/src/gatsby-node.js#L90).

Shouldn't this code iterate over the object to add each key individually?

**Comment by machour** [comment]
Seeing the same thing, the dummy node gets assigned a regular id
