### ISSUE TITLE
Question: does this plugin make XHR requests?

### ISSUE THREAD

**Issue by andreipfeiffer** [thinhle-agilityio/gatsby-source-apiserver#17]
Hey @thinhle-agilityio I have a few questions about how this plugin works internally:

1. does it perform an XHR request from the client? which would require the api server to support CORS, if you make the request from a different origin.

2. if you don't store the JSON locally, what does this plugin do differently than making the request directly from the React Component?

Thank you so much

**Comment by thinhle-agilityio** [comment]
@andreipfeiffer 
1. Yes, it is XHR request from the build time, no need CORS support
2. Again, it stores and renders data in build time, it is differ from making request in a React Component (client runtime)

**Comment by andreipfeiffer** [comment]
Got it. Thank you for the clarification.

I guess that with Gatsby, you cannot load dynamic data (at runtime), without making the requests from the React Component, which requires CORS (unless you proxy requests).

**Comment by thinhle-agilityio** [comment]
Actually, you can load dynamic data (at runtime). It just works like a normal React application. It's not relate to this plugin

**Comment by andreipfeiffer** [comment]
Exactly. Thanks again.
