### ISSUE TITLE
Option to refetch data and create updated nodes

### ISSUE THREAD

**Issue by ibraude** [thinhle-agilityio/gatsby-source-apiserver#22]
Hi!
First of all, thank you for this plugin, it's really great. 
I was wondering, is there a way to make another call to the API periodically with setTimeout or by calling it with another function within the deployed gatsby site?

I am using it to fetch data from a Shopify orders API. 
As the data updates every time someone makes an order, I need to be able to fetch fresh data every time that happens or just have it make a call every couple of minutes. 

Had no luck finding a workaround my self, I would really appreciate it if anyone has an idea. 

Thank you again,

**Comment by thinhle-agilityio** [comment]
@ibraude If you want to update data, you have to rebuild the whole system. So for your case, it's dynamic data, not static data anymore. I suggest you should make API call to refetch data, as a normal React application.

**Comment by ibraude** [comment]
@thinhle-agilityio Thanks! ended up using netlify functions to add dynamic data.
