### ISSUE TITLE
Media type field not following Gatsby convention

### ISSUE THREAD

**Issue by jessevdp** [thinhle-agilityio/gatsby-source-apiserver#32]
I noticed that a type created by this plugin contained the field `mediaType` which is not in my data. Having written my own Gatsby plugin I know that the Node interface has a specific place where it expects this field.

```graphql
id: String,
children: Array[String],
parent: String,
fields: Object,
internal: {
  contentDigest: String,
  mediaType: String,
  type: String,
  owner: String,
  fieldOwners: Object,
  content: String,
}
# ... other fields specific to this type of node
```
— _Source: [Gatsby docs on `Node` Interface](https://www.gatsbyjs.org/docs/node-interface/)_

Notice that `mediaType` is a child of `internal`, not field on the first level of the node. When trying to query for the internal media type, `null` is returned because this plugin adds the field outside of the `internal` object.

```json
{
  "data": {
    "myType": {
      "internal": {
        "mediaType": null
      },
      "mediaType": "application/json"
    }
  }
}
```

Following the convention ensures that other plugins know how to handle the nodes created by your plugin, which contributes to the ecosystem of loosely coupled plugins that are the backbone of Gatsby.

In this case, it also keeps metadata out of the way of the user, since most people don't open up that `internal` object too often.

Please consider moving the `mediaType` field to the `internal` object.

**Comment by jessevdp** [comment]
Dug around in the code for a second. Located the place where this is happening. On line `74`.

https://github.com/thinhle-agilityio/gatsby-source-apiserver/blob/51412d0dc50b4c22028bf04e65beb628ec0009b7/src/normalize.js#L69-L79

**Comment by thinhle-agilityio** [comment]
good catch @jessevdp , will update it, thanks for your contribution

**Comment by jessevdp** [comment]
Want me to make the change real quick?

**Comment by jessevdp** [comment]
Supposed this was fixed by https://github.com/thinhle-agilityio/gatsby-source-apiserver/commit/aec30e65c32cf0b02f052469377f85e0af05eea7.
