### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by rileymacisaac** [thinhle-agilityio/gatsby-source-apiserver#44]
I was having a lot of issues with this plugin and decided to start debugging the source.

My error:
```
 ERROR #11321  PLUGIN
"gatsby-source-apiserver" threw an error while running the sourceNodes lifecycle:
Cannot read property 'data' of undefined
TypeError: Cannot read property 'data' of undefined
```

If I change line 27 in fetch.js:
`completeResult.push(...routeData);`
to
`completeResult.push(routeData);`

It works as expected.

**Comment by aileen** [comment]
I'm facing the same issues. Everything works fine for me `v2.1.5`, but updating to `v2.1.6` causes those errors without changing anything else.

Let me know, if I can help providing more information to debug this issue.

**Comment by sn3h** [comment]
> If I change line 27 in fetch.js:
completeResult.push(...routeData);
to
completeResult.push(routeData);

this helped me after 40 minutes of trying to find why my config suddenly stopped working.. thank you
